INSERT INTO users (username, role, status, course, location) VALUES
('alice', 'study buddy', 'available', 'MATH 214', 'Cameron'),
('bob', 'hangout', 'busy', 'PHYS 124', 'Tory'),
('carol', 'study buddy', 'available', 'CMPUT 204', 'Athabasca'),
('david', 'hangout', 'available', 'CMPUT 267', 'CAB'),
('eve', 'study buddy', 'available', 'MATH 214', 'CCIS'),
('frank', 'hangout', 'busy', 'CMPUT 267', 'NREF'),
('grace', 'study buddy', 'available', 'PHYS 124', 'SUB'),
('hannah', 'study buddy', 'busy', 'CMPUT 291', 'BioSci'),
('ian', 'hangout', 'available', 'MATH 214', 'Rutherford'),
('jack', 'study buddy', 'available', 'CMPUT 204', 'ETLC'),
('karen', 'study buddy', 'busy', 'PHYS 124', 'HUB'),
('linda', 'study buddy', 'available', 'MATH 214', 'Chem East'),
('mike', 'hangout', 'busy', 'CMPUT 291', 'CAB'),
('nina', 'study buddy', 'available', 'CMPUT 291', 'CCIS'),
('oliver', 'hangout', 'available', 'CMPUT 204', 'SUB'),
('peter', 'study buddy', 'available', 'MATH 214', 'NREF'),
('rachel', 'study buddy', 'available', 'CMPUT 267', 'Athabasca'),
('sam', 'study buddy', 'busy', 'CMPUT 204', 'ETLC'),
('tina', 'hangout', 'available', 'CMPUT 291', 'BioSci'),
('uma', 'study buddy', 'available', 'PHYS 124', 'CCIS'),
('victor', 'study buddy', 'busy', 'CMPUT 267', 'CAB'),
('wendy', 'hangout', 'available', 'MATH 214', 'SUB'),
('xander', 'study buddy', 'available', 'CMPUT 204', 'NREF'),
('yara', 'study buddy', 'busy', 'PHYS 124', 'Tory'),
('zoe', 'hangout', 'available', 'CMPUT 291', 'ETLC'),
('amy', 'study buddy', 'available', 'MATH 214', 'Chem West'),
('ben', 'hangout', 'busy', 'CMPUT 204', 'CCIS'),
('chris', 'study buddy', 'available', 'CMPUT 291', 'CAB'),
('diana', 'study buddy', 'available', 'PHYS 124', 'Rutherford'),
('elena', 'hangout', 'available', 'CMPUT 267', 'SUB'),
('felix', 'study buddy', 'busy', 'MATH 214', 'Athabasca'),
('george', 'hangout', 'available', 'PHYS 124', 'BioSci'),
('harry', 'study buddy', 'available', 'CMPUT 204', 'ETLC'),
('irene', 'study buddy', 'busy', 'MATH 214', 'NREF'),
('john', 'hangout', 'available', 'CMPUT 267', 'CAB'),
('kate', 'study buddy', 'available', 'PHYS 124', 'CCIS'),
('leo', 'hangout', 'busy', 'CMPUT 291', 'SUB'),
('mona', 'study buddy', 'available', 'CMPUT 204', 'Athabasca'),
('nancy', 'study buddy', 'busy', 'PHYS 124', 'Rutherford'),
('omar', 'hangout', 'available', 'MATH 214', 'NREF'),
('paula', 'study buddy', 'available', 'CMPUT 267', 'Tory'),
('raj', 'hangout', 'busy', 'CMPUT 204', 'CCIS'),
('sara', 'study buddy', 'available', 'PHYS 124', 'Chem East'),
('tim', 'hangout', 'available', 'MATH 214', 'ETLC'),
('ursula', 'study buddy', 'busy', 'PHYS 124', 'BioSci'),
('vince', 'hangout', 'available', 'CMPUT 291', 'SUB'),
('wanda', 'study buddy', 'available', 'MATH 214', 'Tory'),
('xena', 'study buddy', 'busy', 'CMPUT 204', 'CAB'),
('yusuf', 'hangout', 'available', 'CMPUT 267', 'NREF');
