INSERT INTO users (deviceID, username, role, status, course, location, landmark) VALUES
('user01', 'alice', 'study buddy', 'available', 'Math 101', 'Cameron', '2nd Floor'),
('user02', 'bob', 'hangout', 'busy', 'Physics 102', 'Tory', 'Room 110'),
('user03', 'carol', 'study buddy', 'available', 'CMPUT 204', 'Athabasca', '3rd Floor'),
('user04', 'david', 'hangout', 'available', 'Biology 200', 'CAB', 'Basement'),
('user05', 'eve', 'study buddy', 'available', 'Chemistry 101', 'CCIS', 'Room L1-140'),
('user06', 'frank', 'hangout', 'busy', 'CMPUT 267', 'NREF', '4th Floor'),
('user07', 'grace', 'study buddy', 'available', 'PHYS 124', 'SUB', '2nd Floor'),
('user08', 'hannah', 'study buddy', 'busy', 'English 105', 'BioSci', '5th Floor'),
('user09', 'ian', 'hangout', 'available', 'Math 214', 'Rutherford', 'Room 301'),
('user10', 'jack', 'study buddy', 'available', 'STAT 151', 'ETLC', '2nd Floor'),
('user11', 'karen', 'study buddy', 'busy', 'Sociology 101', 'HUB', 'Common Area'),
('user12', 'linda', 'study buddy', 'available', 'History 210', 'Chem East', 'Room 220'),
('user13', 'mike', 'hangout', 'busy', 'Psych 104', 'CAB', '4th Floor'),
('user14', 'nina', 'study buddy', 'available', 'CMPUT 291', 'CCIS', '2nd Floor'),
('user15', 'oliver', 'hangout', 'available', 'CMPUT 174', 'SUB', '1st Floor'),
('user16', 'peter', 'study buddy', 'available', 'Math 115', 'NREF', 'Room 420'),
('user17', 'quinn', 'hangout', 'busy', 'Biology 107', 'Tory', 'Room 215'),
('user18', 'rachel', 'study buddy', 'available', 'Chemistry 101', 'Athabasca', '1st Floor'),
('user19', 'sam', 'study buddy', 'busy', 'CMPUT 366', 'ETLC', '3rd Floor'),
('user20', 'tina', 'hangout', 'available', 'Anthropology 101', 'BioSci', 'Room 120'),
('user21', 'uma', 'study buddy', 'available', 'Physics 124', 'CCIS', 'Room L2-200'),
('user22', 'victor', 'study buddy', 'busy', 'CMPUT 403', 'CAB', 'Room 305'),
('user23', 'wendy', 'hangout', 'available', 'Math 125', 'SUB', 'Basement'),
('user24', 'xander', 'study buddy', 'available', 'CMPUT 379', 'NREF', '5th Floor'),
('user25', 'yara', 'study buddy', 'busy', 'Sociology 201', 'Tory', 'Room 101'),
('user26', 'zoe', 'hangout', 'available', 'Physics 102', 'ETLC', 'Room 215'),
('user27', 'amy', 'study buddy', 'available', 'Math 117', 'Chem West', '2nd Floor'),
('user28', 'ben', 'hangout', 'busy', 'CMPUT 391', 'CCIS', 'Room L1-150'),
('user29', 'chris', 'study buddy', 'available', 'Biology 300', 'CAB', '3rd Floor'),
('user30', 'diana', 'study buddy', 'available', 'History 100', 'Rutherford', '4th Floor'),
('user31', 'elena', 'hangout', 'available', 'CMPUT 249', 'SUB', 'Common Area'),
('user32', 'felix', 'study buddy', 'busy', 'Psych 202', 'Athabasca', '2nd Floor'),
('user33', 'george', 'hangout', 'available', 'Anthropology 104', 'BioSci', 'Room 310'),
('user34', 'harry', 'study buddy', 'available', 'CMPUT 275', 'ETLC', 'Basement'),
('user35', 'irene', 'study buddy', 'busy', 'Math 120', 'NREF', '4th Floor'),
('user36', 'john', 'hangout', 'available', 'CMPUT 331', 'CAB', 'Room 210'),
('user37', 'kate', 'study buddy', 'available', 'Physics 101', 'CCIS', 'Room L1-120'),
('user38', 'leo', 'hangout', 'busy', 'Chemistry 110', 'SUB', '2nd Floor'),
('user39', 'mona', 'study buddy', 'available', 'Biology 220', 'Athabasca', '1st Floor'),
('user40', 'nancy', 'study buddy', 'busy', 'Sociology 250', 'Rutherford', 'Room 205'),
('user41', 'omar', 'hangout', 'available', 'Math 213', 'NREF', 'Room 330'),
('user42', 'paula', 'study buddy', 'available', 'Psych 105', 'Tory', 'Basement'),
('user43', 'raj', 'hangout', 'busy', 'CMPUT 494', 'CCIS', '2nd Floor'),
('user44', 'sara', 'study buddy', 'available', 'Physics 121', 'Chem East', 'Room 130'),
('user45', 'tim', 'hangout', 'available', 'Math 250', 'ETLC', '3rd Floor'),
('user46', 'ursula', 'study buddy', 'busy', 'Anthropology 202', 'BioSci', 'Room 410'),
('user47', 'vince', 'hangout', 'available', 'CMPUT 210', 'SUB', '1st Floor'),
('user48', 'wanda', 'study buddy', 'available', 'History 205', 'Tory', 'Room 215'),
('user49', 'xena', 'study buddy', 'busy', 'CMPUT 354', 'CAB', '4th Floor'),
('user50', 'yusuf', 'hangout', 'available', 'Psych 101', 'NREF', 'Basement');
